"""Generated Pydantic v2 models for IDOP SharePoint Lists.

DO NOT EDIT DIRECTLY. Generated by scripts/generate_pydantic_models.py.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class SharePointItem(BaseModel):
    """Standard base class for all IDOP SharePoint list items."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int | None = Field(default=None, alias="ID")
    title: str | None = Field(default=None, alias="Title")
    created: datetime | None = Field(default=None, alias="Created")
    modified: datetime | None = Field(default=None, alias="Modified")
    author: dict[str, Any] | str | int | None = Field(default=None, alias="Author")
    editor: dict[str, Any] | str | int | None = Field(default=None, alias="Editor")


class AllocationRulesItem(SharePointItem):
    """Quy tắc phân bổ chi phí"""

    rule_name: str | None = Field(default=None, alias="RuleName", description='RuleName')
    description: str | None = Field(default=None, alias="Description", description='Description')

class BankAccountsItem(SharePointItem):
    """Tài khoản ngân hàng"""

    bank_name: str | None = Field(default=None, alias="BankName", description='BankName')
    account_number: str | None = Field(default=None, alias="AccountNumber", description='AccountNumber')
    account_name: str | None = Field(default=None, alias="AccountName", description='AccountName')
    currency: Literal['VND', 'USD', 'EUR'] | None = Field(default=None, alias="Currency", description='Currency')

class DocumentRequirementsItem(SharePointItem):
    """Yêu cầu hồ sơ chứng từ"""

    requirement_name: str | None = Field(default=None, alias="RequirementName", description='RequirementName')
    description: str | None = Field(default=None, alias="Description", description='Description')
    applies_to: Literal['Contract', 'Invoice', 'Expense'] | None = Field(default=None, alias="AppliesTo", description='AppliesTo')

class ExpenseChecklistsItem(SharePointItem):
    """Checklist kiểm tra chi phí"""

    expense_id: int | dict[str, Any] | None = Field(default=None, alias="ExpenseId", description='ExpenseId')
    checklist_item: str | None = Field(default=None, alias="ChecklistItem", description='ChecklistItem')
    is_completed: bool | None = Field(default=False, alias="IsCompleted", description='IsCompleted')

class ExpensesItem(SharePointItem):
    """Chi phí dự án"""

    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='ProjectId')
    expense_type: dict[str, Any] | str | None = Field(default=None, alias="ExpenseType", description='ExpenseType')
    currency: Literal['VND', 'USD', 'EUR'] | None = Field(default=None, alias="Currency", description='Currency')
    vat_rate: float | int | None = Field(default=None, alias="VATRate", description='VATRate')
    gross_amount: float | int | None = Field(default=None, alias="GrossAmount", description='GrossAmount')
    net_amount: float | int | None = Field(default=None, alias="NetAmount", description='NetAmount')
    expense_date: datetime | None = Field(default=None, alias="ExpenseDate", description='ExpenseDate')

class FinancialPlansItem(SharePointItem):
    """Kế hoạch tài chính"""

    plan_name: str | None = Field(default=None, alias="PlanName", description='PlanName')
    year: float | int | None = Field(default=None, alias="Year", description='Year')
    total_budget: float | int | None = Field(default=None, alias="TotalBudget", description='TotalBudget')

class InputInvoicesItem(SharePointItem):
    """Hóa đơn đầu vào"""

    vendor_id: int | dict[str, Any] | None = Field(default=None, alias="VendorId", description='VendorId')
    invoice_number: str | None = Field(default=None, alias="InvoiceNumber", description='InvoiceNumber')
    currency: Literal['VND', 'USD', 'EUR'] | None = Field(default=None, alias="Currency", description='Currency')
    vat_rate: float | int | None = Field(default=None, alias="VATRate", description='VATRate')
    gross_amount: float | int | None = Field(default=None, alias="GrossAmount", description='GrossAmount')
    net_amount: float | int | None = Field(default=None, alias="NetAmount", description='NetAmount')
    invoice_date: datetime | None = Field(default=None, alias="InvoiceDate", description='InvoiceDate')

class InvoiceRequestsItem(SharePointItem):
    """Yêu cầu xuất hóa đơn"""

    contract_id: int | dict[str, Any] | None = Field(default=None, alias="ContractId", description='ContractId')
    request_date: datetime | None = Field(default=None, alias="RequestDate", description='RequestDate')
    amount: float | int | None = Field(default=None, alias="Amount", description='Amount')
    currency: Literal['VND', 'USD', 'EUR'] | None = Field(default=None, alias="Currency", description='Currency')

class OutgoingInvoicesItem(SharePointItem):
    """Hóa đơn đầu ra"""

    contract_id: int | dict[str, Any] | None = Field(default=None, alias="ContractId", description='ContractId')
    invoice_number: str | None = Field(default=None, alias="InvoiceNumber", description='InvoiceNumber')
    currency: Literal['VND', 'USD', 'EUR'] | None = Field(default=None, alias="Currency", description='Currency')
    vat_rate: float | int | None = Field(default=None, alias="VATRate", description='VATRate')
    gross_amount: float | int | None = Field(default=None, alias="GrossAmount", description='GrossAmount')
    net_amount: float | int | None = Field(default=None, alias="NetAmount", description='NetAmount')
    invoice_date: datetime | None = Field(default=None, alias="InvoiceDate", description='InvoiceDate')

class SharedCostAllocationsItem(SharePointItem):
    """Phân bổ chi phí chung"""

    expense_id: int | dict[str, Any] | None = Field(default=None, alias="ExpenseId", description='ExpenseId')
    allocation_rule_id: int | dict[str, Any] | None = Field(default=None, alias="AllocationRuleId", description='AllocationRuleId')
    amount: float | int | None = Field(default=None, alias="Amount", description='Số tiền phân bổ (VND)')
    allocation_category: dict[str, Any] | str | None = Field(default=None, alias="AllocationCategory", description='Hạng mục phân bổ 3 tầng')

class VendorsItem(SharePointItem):
    """Nhà cung cấp"""

    vendor_name: str | None = Field(default=None, alias="VendorName", description='VendorName')
    vendor_code: str | None = Field(default=None, alias="VendorCode", description='VendorCode')
    service_type: dict[str, Any] | str | None = Field(default=None, alias="ServiceType", description='ServiceType')

class AssetsItem(SharePointItem):
    """Tài sản"""

    asset_name: str | None = Field(default=None, alias="AssetName", description='AssetName')
    asset_code: str | None = Field(default=None, alias="AssetCode", description='AssetCode')
    assigned_to: int | dict[str, Any] | None = Field(default=None, alias="AssignedTo", description='AssignedTo')
    purchase_date: datetime | None = Field(default=None, alias="PurchaseDate", description='PurchaseDate')
    original_value: float | int | None = Field(default=None, alias="OriginalValue", description='OriginalValue')
    depreciation_rate: float | int | None = Field(default=None, alias="DepreciationRate", description='DepreciationRate')
    accumulated_depreciation: float | int | None = Field(default=None, alias="AccumulatedDepreciation", description='AccumulatedDepreciation')
    serial_number: str | None = Field(default=None, alias="SerialNumber", description='SerialNumber')
    location: str | None = Field(default=None, alias="Location", description='Location')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Status')

class BenefitPackagesItem(SharePointItem):
    """Gói phúc lợi"""

    package_name: str | None = Field(default=None, alias="PackageName", description='PackageName')
    description: str | None = Field(default=None, alias="Description", description='Description')

class CertificationsItem(SharePointItem):
    """Chứng chỉ"""

    employee_id: int | dict[str, Any] | None = Field(default=None, alias="EmployeeId", description='EmployeeId')
    certification_name: str | None = Field(default=None, alias="CertificationName", description='CertificationName')
    issued_by: str | None = Field(default=None, alias="IssuedBy", description='IssuedBy')
    issue_date: datetime | None = Field(default=None, alias="IssueDate", description='IssueDate')
    expiry_date: datetime | None = Field(default=None, alias="ExpiryDate", description='ExpiryDate')

class DepartmentsItem(SharePointItem):
    """Phòng ban"""

    department_name: str | None = Field(default=None, alias="DepartmentName", description='DepartmentName')
    department_code: str | None = Field(default=None, alias="DepartmentCode", description='DepartmentCode')
    parent_department_id: int | dict[str, Any] | None = Field(default=None, alias="ParentDepartmentId", description='ParentDepartmentId')
    manager: dict[str, Any] | str | int | None = Field(default=None, alias="Manager", description='Manager')

class EmployeeBenefitsItem(SharePointItem):
    """Phúc lợi nhân viên"""

    employee_id: int | dict[str, Any] | None = Field(default=None, alias="EmployeeId", description='EmployeeId')
    benefit_package_id: int | dict[str, Any] | None = Field(default=None, alias="BenefitPackageId", description='BenefitPackageId')
    start_date: datetime | None = Field(default=None, alias="StartDate", description='StartDate')
    end_date: datetime | None = Field(default=None, alias="EndDate", description='EndDate')

class EmployeeHistoryItem(SharePointItem):
    """Lịch sử nhân viên"""

    employee_id: int | dict[str, Any] | None = Field(default=None, alias="EmployeeId", description='EmployeeId')
    start_date: datetime | None = Field(default=None, alias="StartDate", description='StartDate')
    end_date: datetime | None = Field(default=None, alias="EndDate", description='EndDate')
    is_current: bool | None = Field(default=False, alias="IsCurrent", description='IsCurrent')

class EmployeesItem(SharePointItem):
    """Nhân viên"""

    full_name: str | None = Field(default=None, alias="FullName", description='FullName')
    employee_code: str | None = Field(default=None, alias="EmployeeCode", description='EmployeeCode')
    department_id: int | dict[str, Any] | None = Field(default=None, alias="DepartmentId", description='DepartmentId')
    position: str | None = Field(default=None, alias="Position", description='Position')
    hire_date: datetime | None = Field(default=None, alias="HireDate", description='HireDate')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Status')

class EmploymentContractsItem(SharePointItem):
    """Hợp đồng lao động"""

    employee_id: int | dict[str, Any] | None = Field(default=None, alias="EmployeeId", description='EmployeeId')
    contract_number: str | None = Field(default=None, alias="ContractNumber", description='ContractNumber')
    start_date: datetime | None = Field(default=None, alias="StartDate", description='StartDate')
    end_date: datetime | None = Field(default=None, alias="EndDate", description='EndDate')
    contract_type: Literal['Full-time', 'Part-time', 'Internship', 'Freelance'] | None = Field(default=None, alias="ContractType", description='ContractType')

class MaintenanceLogsItem(SharePointItem):
    """Nhật ký bảo trì tài sản"""

    asset_id: int | dict[str, Any] | None = Field(default=None, alias="AssetId", description='AssetId')
    maintenance_date: datetime | None = Field(default=None, alias="MaintenanceDate", description='MaintenanceDate')
    description: str | None = Field(default=None, alias="Description", description='Description')
    performed_by: dict[str, Any] | str | int | None = Field(default=None, alias="PerformedBy", description='PerformedBy')

class ProjectMembersItem(SharePointItem):
    """Thành viên dự án"""

    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='ProjectId')
    employee_id: int | dict[str, Any] | None = Field(default=None, alias="EmployeeId", description='EmployeeId')
    role: str | None = Field(default=None, alias="Role", description='Vai trò nhiệm vụ')
    bim_role: dict[str, Any] | str | None = Field(default=None, alias="BIMRole", description='Chức danh BIM (ISO 19650)')

class RewardsItem(SharePointItem):
    """Khen thưởng"""

    employee_id: int | dict[str, Any] | None = Field(default=None, alias="EmployeeId", description='EmployeeId')
    reward_title: str | None = Field(default=None, alias="RewardTitle", description='RewardTitle')
    reward_date: datetime | None = Field(default=None, alias="RewardDate", description='RewardDate')
    description: str | None = Field(default=None, alias="Description", description='Description')

class TimesheetsItem(SharePointItem):
    """Bảng chấm công"""

    employee_id: int | dict[str, Any] | None = Field(default=None, alias="EmployeeId", description='EmployeeId')
    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='Dự án')
    date: datetime | None = Field(default=None, alias="Date", description='Date')
    hours_worked: float | int | None = Field(default=None, alias="HoursWorked", description='HoursWorked')
    notes: str | None = Field(default=None, alias="Notes", description='Notes')

class MeasurablesItem(SharePointItem):
    """Chỉ số đo lường"""

    metric_name: str | None = Field(default=None, alias="MetricName", description='MetricName')
    unit: str | None = Field(default=None, alias="Unit", description='Unit')
    description: str | None = Field(default=None, alias="Description", description='Description')

class OKRSKeyResultsItem(SharePointItem):
    """Kết quả then chốt OKR"""

    objective_id: int | dict[str, Any] | None = Field(default=None, alias="ObjectiveId", description='ObjectiveId')
    key_result_title: str | None = Field(default=None, alias="KeyResultTitle", description='KeyResultTitle')
    target_value: float | int | None = Field(default=None, alias="TargetValue", description='TargetValue')
    current_value: float | int | None = Field(default=None, alias="CurrentValue", description='CurrentValue')

class OKRSObjectivesItem(SharePointItem):
    """Mục tiêu OKR"""

    objective_title: str | None = Field(default=None, alias="ObjectiveTitle", description='ObjectiveTitle')
    owner: dict[str, Any] | str | int | None = Field(default=None, alias="Owner", description='Owner')
    quarter_id: int | dict[str, Any] | None = Field(default=None, alias="QuarterId", description='QuarterId')
    parent_objective_id: int | dict[str, Any] | None = Field(default=None, alias="ParentObjectiveId", description='ParentObjectiveId')
    department_id: int | dict[str, Any] | None = Field(default=None, alias="DepartmentId", description='DepartmentId')
    description: str | None = Field(default=None, alias="Description", description='Description')

class QuartersItem(SharePointItem):
    """Quý"""

    year: float | int | None = Field(default=None, alias="Year", description='Year')
    quarter: Literal['Q1', 'Q2', 'Q3', 'Q4'] | None = Field(default=None, alias="Quarter", description='Quarter')
    start_date: datetime | None = Field(default=None, alias="StartDate", description='StartDate')
    end_date: datetime | None = Field(default=None, alias="EndDate", description='EndDate')

class ScorecardDataItem(SharePointItem):
    """Dữ liệu scorecard định kỳ"""

    metric_id: int | dict[str, Any] | None = Field(default=None, alias="MetricId", description='MetricId')
    period_type: Literal['Week', 'Month', 'Quarter', 'Year'] | None = Field(default=None, alias="PeriodType", description='PeriodType')
    period_key: str | None = Field(default=None, alias="PeriodKey", description='PeriodKey')
    value: float | int | None = Field(default=None, alias="Value", description='Value')

class ActivitiesItem(SharePointItem):
    """Hoạt động CRM/Marketing/R&D/Admin"""

    activity_name: str | None = Field(default=None, alias="ActivityName", description='ActivityName')
    activity_type: Literal['CRM', 'PotentialProject', 'Marketing', 'R&D', 'Admin'] | None = Field(default=None, alias="ActivityType", description='ActivityType')
    owner: dict[str, Any] | str | int | None = Field(default=None, alias="Owner", description='Người phụ trách')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Trạng thái')

class AssignmentDetailsItem(SharePointItem):
    """Chi tiết phân công nhân sự và ràng buộc pháp lý theo Phiếu giao việc PGV"""

    assignment_id: int | dict[str, Any] | None = Field(default=None, alias="AssignmentId", description='Phiếu giao việc (PGV)')
    contract_scope_id: int | dict[str, Any] | None = Field(default=None, alias="ContractScopeId", description='Hạng mục hợp đồng')
    scope_dept_alloc_id: int | dict[str, Any] | None = Field(default=None, alias="ScopeDeptAllocId", description='Phân bổ đơn vị hạng mục')
    discipline_code: dict[str, Any] | str | None = Field(default=None, alias="DisciplineCode", description='Bộ môn chuyên ngành (ARC, STR, EL, HV, FP...)')
    generic_role_name: str | None = Field(default=None, alias="GenericRoleName", description='Tên chức danh chuyên môn generic')
    assigned_technical_chief_user: dict[str, Any] | str | int | None = Field(default=None, alias="AssignedTechnicalChiefUser", description='Chủ trì kỹ thuật được phân công')
    resolved_legal_role: str | None = Field(default=None, alias="ResolvedLegalRole", description='Chức danh pháp lý quy định (Luật 135/2025)')
    technical_chief_cert_no: str | None = Field(default=None, alias="TechnicalChiefCertNo", description='Số CCHN của Chủ trì kỹ thuật Scope')
    requires_cert_check: bool | None = Field(default=False, alias="RequiresCertCheck", description='Yêu cầu kiểm tra chứng chỉ hành nghề')
    discipline_lead: dict[str, Any] | str | int | None = Field(default=None, alias="DisciplineLead", description='Chủ trì bộ môn')
    team_members: list[dict[str, Any] | str | int] | None = Field(default_factory=list, alias="TeamMembers", description='Thành viên nhóm thực hiện')
    qc_checker: dict[str, Any] | str | int | None = Field(default=None, alias="QCChecker", description='Người kiểm tra chất lượng (QA/QC)')
    allocated_hours: float | int | None = Field(default=None, alias="AllocatedHours", description='Số giờ phân bổ')
    task_description: str | None = Field(default=None, alias="TaskDescription", description='Mô tả công việc chi tiết')
    hours_worked: float | int | None = Field(default=None, alias="HoursWorked", description='Số giờ thực tế đã làm')
    notes: str | None = Field(default=None, alias="Notes", description='Ghi chú')

class CDEDocumentsItem(SharePointItem):
    """Chỉ mục tài liệu CDE theo dự án, quản lý siêu dữ liệu ISO 19650 & liên kết đến thư mục/URL thực tế."""

    title: str | None = Field(default=None, alias="Title", description='Tiêu đề')
    project: int | dict[str, Any] | None = Field(default=None, alias="Project", description='Dự án')
    project_code: str | None = Field(default=None, alias="ProjectCode", description='Mã dự án')
    originator: str | None = Field(default=None, alias="Originator", description='Tác giả / Đơn vị tạo')
    zone_volume: str | None = Field(default=None, alias="ZoneVolume", description='Phân khu / Khối công trình')
    level_location: str | None = Field(default=None, alias="LevelLocation", description='Cao độ / Tầng')
    document_code: str | None = Field(default=None, alias="DocumentCode", description='Mã tài liệu')
    iso_document_name: str | None = Field(default=None, alias="IsoDocumentName", description='Tên tệp chuẩn ISO 19650')
    document_type: dict[str, Any] | str | None = Field(default=None, alias="DocumentType", description='Loại tài liệu')
    discipline: dict[str, Any] | str | None = Field(default=None, alias="Discipline", description='Chuyên ngành')
    service_type: dict[str, Any] | str | None = Field(default=None, alias="ServiceType", description='Loại hình dịch vụ')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Trạng thái')
    approval_status: Literal['S0', 'S1', 'S2', 'S3', 'A1'] | None = Field(default=None, alias="ApprovalStatus", description='Trạng thái phê duyệt CDE')
    version: str | None = Field(default=None, alias="Version", description='Phiên bản')
    file_url: dict[str, Any] | str | None = Field(default=None, alias="FileUrl", description='Liên kết tệp')
    submission: int | dict[str, Any] | None = Field(default=None, alias="Submission", description='Hồ sơ nộp')
    retention_until: datetime | None = Field(default=None, alias="RetentionUntil", description='Lưu đến ngày')
    owner: dict[str, Any] | str | int | None = Field(default=None, alias="Owner", description='Người phụ trách')

class ContractScopesItem(SharePointItem):
    """Hạng mục chi tiết thuộc Hợp đồng theo Nhóm HĐKT (Phụ lục 7 & Phụ lục 8 QCCTNB 3209)"""

    contract_id: int | dict[str, Any] | None = Field(default=None, alias="ContractId", description='Hợp đồng')
    nhom_hop_dong_kt: dict[str, Any] | str | None = Field(default=None, alias="NhomHopDongKT", description='Nhóm HĐKT (Phụ lục 7)')
    scope_name: str | None = Field(default=None, alias="ScopeName", description='Tên hạng mục / Gói công việc')
    amount_before_vat: float | int | None = Field(default=None, alias="AmountBeforeVAT", description='Giá trị trước thuế (VND)')
    ty_le_giao_don_vi: float | int | None = Field(default=None, alias="TyLeGiaoDonVi", description='Tỷ lệ giao đơn vị (%)')
    gia_tri_giao_don_vi: float | int | None = Field(default=None, alias="GiaTriGiaoDonVi", description='Kinh phí giao đơn vị (VND)')
    ty_le_vien_cpql: float | int | None = Field(default=None, alias="TyLeVienCPQL", description='Tỷ lệ Viện CPQL (%)')
    gia_tri_vien_cpql: float | int | None = Field(default=None, alias="GiaTriVienCPQL", description='Kinh phí Viện CPQL (VND)')
    ty_le_vien_khts: float | int | None = Field(default=None, alias="TyLeVienKHTS", description='Tỷ lệ Viện KHTS (%)')
    gia_tri_vien_khts: float | int | None = Field(default=None, alias="GiaTriVienKHTS", description='Kinh phí Viện KHTS (VND)')
    khung_nhan_cong_min: float | int | None = Field(default=None, alias="KhungNhanCongMin", description='Khung Nhân công Min (%)')
    khung_nhan_cong_max: float | int | None = Field(default=None, alias="KhungNhanCongMax", description='Khung Nhân công Max (%)')
    scope_chief_user: dict[str, Any] | str | int | None = Field(default=None, alias="ScopeChiefUser", description='Chủ nhiệm theo hoạt động XD (Điều 3.2b)')
    scope_chief_cert_no: str | None = Field(default=None, alias="ScopeChiefCertNo", description='Số CCHN Chủ nhiệm')

class ContractsItem(SharePointItem):
    """Hợp đồng"""

    contract_code: str | None = Field(default=None, alias="ContractCode", description='ContractCode')
    contract_name: str | None = Field(default=None, alias="ContractName", description='ContractName')
    customer_id: int | dict[str, Any] | None = Field(default=None, alias="CustomerId", description='CustomerId')
    currency: Literal['VND', 'USD', 'EUR'] | None = Field(default=None, alias="Currency", description='Currency')
    vat_rate: float | int | None = Field(default=None, alias="VATRate", description='VATRate')
    gross_amount: float | int | None = Field(default=None, alias="GrossAmount", description='GrossAmount')
    net_amount: float | int | None = Field(default=None, alias="NetAmount", description='NetAmount')
    primary_contract_group: dict[str, Any] | str | None = Field(default=None, alias="PrimaryContractGroup", description='Nhóm HĐKT chính (Phụ lục 7)')
    cooperating_department: dict[str, Any] | str | None = Field(default=None, alias="CooperatingDepartment", description='Đơn vị phối hợp (Viện IBST)')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Trạng thái')
    loai_ky_ket: Literal['VienKy', 'CCBAKy', 'LienDanh'] | None = Field(default=None, alias="LoaiKyKet", description='Loại ký kết HĐ')
    sign_date: datetime | None = Field(default=None, alias="SignDate", description='Ngày ký hợp đồng')
    opportunity_id: int | dict[str, Any] | None = Field(default=None, alias="OpportunityId", description='Cơ hội kinh doanh (CRM)')
    service_type: dict[str, Any] | str | None = Field(default=None, alias="ServiceType", description='Loại hình dịch vụ chính')
    document_url: dict[str, Any] | str | None = Field(default=None, alias="DocumentUrl", description='Liên kết file HĐ (OneDrive)')

class JobAssignmentsItem(SharePointItem):
    """Phân công công việc (Phiếu Giao Việc PGV)"""

    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='Dự án')
    contract_scope_id: int | dict[str, Any] | None = Field(default=None, alias="ContractScopeId", description='Hạng mục hợp đồng')
    employee_id: int | dict[str, Any] | None = Field(default=None, alias="EmployeeId", description='Nhân viên phân công')
    role: str | None = Field(default=None, alias="Role", description='Vai trò giao việc')
    contract_lead_user: dict[str, Any] | str | int | None = Field(default=None, alias="ContractLeadUser", description='Chủ trì hợp đồng (PM)')
    scope_chiefs_summary: str | None = Field(default=None, alias="ScopeChiefsSummary", description='Tổng hợp Chủ nhiệm KT theo Scope (Rollup)')
    financial_officer_user: dict[str, Any] | str | int | None = Field(default=None, alias="FinancialOfficerUser", description='Phụ trách tài chính (nếu có)')
    start_date: datetime | None = Field(default=None, alias="StartDate", description='Ngày bắt đầu')
    end_date: datetime | None = Field(default=None, alias="EndDate", description='Ngày kết thúc')
    total_allocated_hours: float | int | None = Field(default=None, alias="TotalAllocatedHours", description='Tổng số giờ phân bổ (Rollup)')
    total_disciplines_count: float | int | None = Field(default=None, alias="TotalDisciplinesCount", description='Số bộ môn tham gia (Rollup)')
    total_staff_count: float | int | None = Field(default=None, alias="TotalStaffCount", description='Tổng số cán bộ tham gia (Rollup)')
    discipline_team_summary: str | None = Field(default=None, alias="DisciplineTeamSummary", description='Tổng hợp đội ngũ theo bộ môn (Rollup)')

class LessonsLearnedItem(SharePointItem):
    """Bài học kinh nghiệm"""

    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='ProjectId')
    lesson_title: str | None = Field(default=None, alias="LessonTitle", description='LessonTitle')
    description: str | None = Field(default=None, alias="Description", description='Description')
    category: dict[str, Any] | str | None = Field(default=None, alias="Category", description='Category')

class ProjectHistoryItem(SharePointItem):
    """Lịch sử dự án"""

    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='ProjectId')
    change_date: datetime | None = Field(default=None, alias="ChangeDate", description='ChangeDate')
    change_description: str | None = Field(default=None, alias="ChangeDescription", description='ChangeDescription')
    is_current: bool | None = Field(default=False, alias="IsCurrent", description='IsCurrent')

class ProjectIssuesItem(SharePointItem):
    """Vấn đề dự án"""

    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='ProjectId')
    issue_title: str | None = Field(default=None, alias="IssueTitle", description='IssueTitle')
    priority: Literal['High', 'Medium', 'Low'] | None = Field(default=None, alias="Priority", description='Mức độ ưu tiên')
    description: str | None = Field(default=None, alias="Description", description='Description')
    owner: dict[str, Any] | str | int | None = Field(default=None, alias="Owner", description='Người phụ trách')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Trạng thái')
    reported_date: datetime | None = Field(default=None, alias="ReportedDate", description='ReportedDate')
    resolved_date: datetime | None = Field(default=None, alias="ResolvedDate", description='ResolvedDate')

class ProjectRisksItem(SharePointItem):
    """Rủi ro dự án"""

    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='ProjectId')
    risk_title: str | None = Field(default=None, alias="RiskTitle", description='RiskTitle')
    severity: Literal['Low', 'Medium', 'High'] | None = Field(default=None, alias="Severity", description='Severity')
    mitigation_plan: str | None = Field(default=None, alias="MitigationPlan", description='MitigationPlan')
    owner: dict[str, Any] | str | int | None = Field(default=None, alias="Owner", description='Người phụ trách')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Trạng thái')

class ProjectsItem(SharePointItem):
    """Dự án thực thi"""

    project_code: str | None = Field(default=None, alias="ProjectCode", description='Mã dự án')
    project_name: str | None = Field(default=None, alias="ProjectName", description='Tên dự án')
    national_project_id: str | None = Field(default=None, alias="NationalProjectID", description='Mã dự án quốc gia / Viện IBST')
    contract_id: int | dict[str, Any] | None = Field(default=None, alias="ContractId", description='Hợp đồng')
    budget: float | int | None = Field(default=None, alias="Budget", description='Ngân sách dự án (VND)')
    service_type: dict[str, Any] | str | None = Field(default=None, alias="ServiceType", description='Loại hình dịch vụ')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Trạng thái')
    cooperating_department: dict[str, Any] | str | None = Field(default=None, alias="CooperatingDepartment", description='Đơn vị phối hợp')
    funding_source: dict[str, Any] | str | None = Field(default=None, alias="FundingSource", description='Nguồn vốn')
    start_date: datetime | None = Field(default=None, alias="StartDate", description='Ngày bắt đầu')
    end_date: datetime | None = Field(default=None, alias="EndDate", description='Ngày kết thúc')

class ScopeDepartmentAllocationsItem(SharePointItem):
    """Phân bổ kinh phí hạng mục hợp đồng theo đơn vị / phòng ban"""

    contract_scope_id: int | dict[str, Any] | None = Field(default=None, alias="ContractScopeId", description='Hạng mục hợp đồng')
    department: dict[str, Any] | str | None = Field(default=None, alias="Department", description='Đơn vị / Phòng ban')
    role: str | None = Field(default=None, alias="Role", description='Vai trò đơn vị')
    allocation_share: float | int | None = Field(default=None, alias="AllocationShare", description='Tỷ lệ phân bổ (%)')
    allocated_amount: float | int | None = Field(default=None, alias="AllocatedAmount", description='Kinh phí phân bổ (VND)')
    department_head: dict[str, Any] | str | int | None = Field(default=None, alias="DepartmentHead", description='Trưởng đơn vị / Trưởng phòng')

class WorkPackagesItem(SharePointItem):
    """Gói công việc"""

    package_name: str | None = Field(default=None, alias="PackageName", description='PackageName')
    project_id: int | dict[str, Any] | None = Field(default=None, alias="ProjectId", description='ProjectId')
    assigned_to: dict[str, Any] | str | int | None = Field(default=None, alias="AssignedTo", description='AssignedTo')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Trạng thái')
    start_date: datetime | None = Field(default=None, alias="StartDate", description='StartDate')
    end_date: datetime | None = Field(default=None, alias="EndDate", description='EndDate')

class ContactsItem(SharePointItem):
    """Liên hệ khách hàng của CCBA"""

    contact_name: str | None = Field(default=None, alias="ContactName", description='ContactName')
    role: dict[str, Any] | str | None = Field(default=None, alias="Role", description='Role')
    email: str | None = Field(default=None, alias="Email", description='Email')
    phone: str | None = Field(default=None, alias="Phone", description='Phone')
    customer: int | dict[str, Any] | None = Field(default=None, alias="Customer", description='Khách hàng')

class CustomersItem(SharePointItem):
    """Danh sách khách hàng của CCBA"""

    customer_name: str | None = Field(default=None, alias="CustomerName", description='Tên khách hàng')
    customer_type: dict[str, Any] | str | None = Field(default=None, alias="CustomerType", description='CustomerType')
    industry: dict[str, Any] | str | None = Field(default=None, alias="Industry", description='Ngành/Lĩnh vực')
    source: dict[str, Any] | str | None = Field(default=None, alias="Source", description='Nguồn')
    contacts: int | dict[str, Any] | None = Field(default=None, alias="Contacts", description='Liên hệ')
    opportunities: int | dict[str, Any] | None = Field(default=None, alias="Opportunities", description='Cơ hội')
    tax_code: str | None = Field(default=None, alias="TaxCode", description='Mã số thuế')
    address: str | None = Field(default=None, alias="Address", description='Địa chỉ')
    phone: str | None = Field(default=None, alias="Phone", description='Điện thoại')
    email: str | None = Field(default=None, alias="Email", description='Email')

class LeadsItem(SharePointItem):
    """Khách hàng tiềm năng từ Microsoft Forms và các nguồn khác"""

    lead_name: str | None = Field(default=None, alias="LeadName", description='LeadName')
    email: str | None = Field(default=None, alias="Email", description='Email')
    phone: str | None = Field(default=None, alias="Phone", description='Phone')
    company: str | None = Field(default=None, alias="Company", description='Company')
    position: str | None = Field(default=None, alias="Position", description='Position')
    source: dict[str, Any] | str | None = Field(default=None, alias="Source", description='Source')
    service_interest: dict[str, Any] | str | None = Field(default=None, alias="ServiceInterest", description='ServiceInterest')
    industry: dict[str, Any] | str | None = Field(default=None, alias="Industry", description='Industry')
    status: Literal['New', 'Contacted', 'Qualified', 'Converted', 'Lost'] | None = Field(default=None, alias="Status", description='Status')
    priority: dict[str, Any] | str | None = Field(default=None, alias="Priority", description='Priority')
    notes: str | None = Field(default=None, alias="Notes", description='Notes')
    project_description: str | None = Field(default=None, alias="ProjectDescription", description='ProjectDescription')
    budget: str | None = Field(default=None, alias="Budget", description='Budget')
    timeline: str | None = Field(default=None, alias="Timeline", description='Timeline')
    assigned_to: dict[str, Any] | str | int | None = Field(default=None, alias="AssignedTo", description='AssignedTo')
    last_contact_date: datetime | None = Field(default=None, alias="LastContactDate", description='LastContactDate')
    next_follow_up_date: datetime | None = Field(default=None, alias="NextFollowUpDate", description='NextFollowUpDate')
    converted_to_opportunity: int | dict[str, Any] | None = Field(default=None, alias="ConvertedToOpportunity", description='ConvertedToOpportunity')
    converted_to_customer: int | dict[str, Any] | None = Field(default=None, alias="ConvertedToCustomer", description='ConvertedToCustomer')
    lead_score: float | int | None = Field(default=None, alias="LeadScore", description='LeadScore')
    form_submission_id: str | None = Field(default=None, alias="FormSubmissionId", description='FormSubmissionId')
    form_response_date: datetime | None = Field(default=None, alias="FormResponseDate", description='FormResponseDate')
    follow_up_sequence_stage: Literal['Initial', 'FirstFollow', 'SecondFollow', 'ThirdFollow', 'Completed'] | None = Field(default=None, alias="FollowUpSequenceStage", description='FollowUpSequenceStage')
    emails_sent: float | int | None = Field(default=None, alias="EmailsSent", description='EmailsSent')
    last_email_sent: datetime | None = Field(default=None, alias="LastEmailSent", description='LastEmailSent')

class OpportunitiesItem(SharePointItem):
    """Cơ hội kinh doanh của CCBA"""

    opportunity_name: str | None = Field(default=None, alias="OpportunityName", description='Tên cơ hội')
    potential_project: int | dict[str, Any] | None = Field(default=None, alias="PotentialProject", description='Tiềm năng dự án')
    customer: int | dict[str, Any] | None = Field(default=None, alias="Customer", description='Khách hàng')
    contact: int | dict[str, Any] | None = Field(default=None, alias="Contact", description='Liên hệ')
    stage: Literal['New', 'Qualification Review', 'Proposal/HSDX', 'Closed - Won', 'Closed - Lost', 'Closed - Not Pursued'] | None = Field(default=None, alias="Stage", description='Giai đoạn')
    participation_decision: Literal['Unknown', 'Yes', 'No'] | None = Field(default=None, alias="ParticipationDecision", description='Quyết định tham gia')
    decision_date: datetime | None = Field(default=None, alias="DecisionDate", description='Ngày quyết định')
    decision_note: str | None = Field(default=None, alias="DecisionNote", description='Ghi chú quyết định')
    decision_email_link: dict[str, Any] | str | None = Field(default=None, alias="DecisionEmailLink", description='Liên kết email quyết định')
    bidding_folder_drive_item_id: str | None = Field(default=None, alias="BiddingFolderDriveItemId", description='ID mục thư mục Hồ sơ thầu')
    bidding_folder_url: dict[str, Any] | str | None = Field(default=None, alias="BiddingFolderUrl", description='URL thư mục Hồ sơ thầu')
    bidding_folder_path: str | None = Field(default=None, alias="BiddingFolderPath", description='Đường dẫn thư mục Hồ sơ thầu')
    bidding_folder_state: Literal['Not Created', 'Creating', 'Created', 'Failed'] | None = Field(default=None, alias="BiddingFolderState", description='Trạng thái thư mục Hồ sơ thầu')
    bidding_folder_phase: Literal['Draft', 'Confirmed', 'Archived'] | None = Field(default=None, alias="BiddingFolderPhase", description='Pha thư mục Hồ sơ thầu')
    bidding_code: str | None = Field(default=None, alias="BiddingCode", description='Mã hồ sơ thầu')
    bid_team: list[dict[str, Any] | str | int] | None = Field(default_factory=list, alias="BidTeam", description='Nhóm dự thầu')
    value: float | int | None = Field(default=None, alias="Value", description='Giá trị')
    probability: float | int | None = Field(default=None, alias="Probability", description='Xác suất')
    adjusted_probability: float | int | None = Field(default=None, alias="AdjustedProbability", description='Xác suất điều chỉnh')
    influence_score: float | int | None = Field(default=None, alias="InfluenceScore", description='Điểm ảnh hưởng')
    risk_flags: list[Literal['InfluenceLow', 'MissingRoles', 'StakeholderOpposition', 'DataGap']] | list[str] | None = Field(default_factory=list, alias="RiskFlags", description='Cờ rủi ro')
    service_mix_summary: str | None = Field(default=None, alias="ServiceMixSummary", description='Tổng hợp dịch vụ')
    expected_close_date: datetime | None = Field(default=None, alias="ExpectedCloseDate", description='Ngày dự kiến chốt')
    status: Literal['Active', 'Closed', 'OnHold'] | None = Field(default=None, alias="Status", description='Trạng thái')
    service_type: dict[str, Any] | str | None = Field(default=None, alias="ServiceType", description='Loại hình dịch vụ')
    industry: dict[str, Any] | str | None = Field(default=None, alias="Industry", description='Ngành/Lĩnh vực')
    source: dict[str, Any] | str | None = Field(default=None, alias="Source", description='Nguồn')
    related_contracts: int | dict[str, Any] | None = Field(default=None, alias="RelatedContracts", description='Hợp đồng liên quan')
    related_projects: int | dict[str, Any] | None = Field(default=None, alias="RelatedProjects", description='Dự án liên quan')
    owner: dict[str, Any] | str | int | None = Field(default=None, alias="Owner", description='Người phụ trách')

class OpportunityServicesItem(SharePointItem):
    """Các dòng dịch vụ chi tiết thuộc một cơ hội"""

    opportunity: int | dict[str, Any] | None = Field(default=None, alias="Opportunity", description='Opportunity')
    service_type: dict[str, Any] | str | None = Field(default=None, alias="ServiceType", description='Loại hình dịch vụ')
    service_description: str | None = Field(default=None, alias="ServiceDescription", description='ServiceDescription')
    estimated_value: float | int | None = Field(default=None, alias="EstimatedValue", description='EstimatedValue')
    probability: float | int | None = Field(default=None, alias="Probability", description='Xác suất')
    status: Literal['Draft', 'Active', 'Negotiating', 'Won', 'Lost', 'Dropped'] | None = Field(default=None, alias="Status", description='Trạng thái')
    planned_start: datetime | None = Field(default=None, alias="PlannedStart", description='PlannedStart')
    planned_end: datetime | None = Field(default=None, alias="PlannedEnd", description='PlannedEnd')

class OpportunityStageHistoryItem(SharePointItem):
    """Lịch sử chuyển stage của Opportunity"""

    opportunity: int | dict[str, Any] | None = Field(default=None, alias="Opportunity", description='Opportunity')
    from_stage: Literal['Lead', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost'] | None = Field(default=None, alias="FromStage", description='FromStage')
    to_stage: Literal['Lead', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost'] | None = Field(default=None, alias="ToStage", description='ToStage')
    days_in_prev_stage: float | int | None = Field(default=None, alias="DaysInPrevStage", description='DaysInPrevStage')
    changed_at: datetime | None = Field(default=None, alias="ChangedAt", description='ChangedAt')
    changed_by: dict[str, Any] | str | int | None = Field(default=None, alias="ChangedBy", description='ChangedBy')

class OpportunityStakeholdersItem(SharePointItem):
    """Stakeholder và mức ảnh hưởng trong từng cơ hội"""

    opportunity: int | dict[str, Any] | None = Field(default=None, alias="Opportunity", description='Opportunity')
    contact: int | dict[str, Any] | None = Field(default=None, alias="Contact", description='Liên hệ')
    role_type: dict[str, Any] | str | None = Field(default=None, alias="RoleType", description='RoleType')
    influence_weight: float | int | None = Field(default=None, alias="InfluenceWeight", description='InfluenceWeight')
    support_level: Literal['Champion', 'Supportive', 'Neutral', 'Opposed'] | None = Field(default=None, alias="SupportLevel", description='SupportLevel')
    engagement_status: Literal['New', 'Nurturing', 'Active', 'AtRisk'] | None = Field(default=None, alias="EngagementStatus", description='EngagementStatus')
    notes: str | None = Field(default=None, alias="Notes", description='Notes')

class PotentialProjectsItem(SharePointItem):
    """Tiềm năng dự án hình thành từ CRM, tiền đề để chuyển thành Projects sau khi ký HĐKT."""

    title: str | None = Field(default=None, alias="Title", description='Tiêu đề')
    opportunity_id: int | dict[str, Any] | None = Field(default=None, alias="OpportunityId", description='Cơ hội CRM')
    customer: int | dict[str, Any] | None = Field(default=None, alias="Customer", description='Khách hàng')
    contact: int | dict[str, Any] | None = Field(default=None, alias="Contact", description='Liên hệ')
    expected_contract_value: float | int | None = Field(default=None, alias="ExpectedContractValue", description='Giá trị HĐ dự kiến')
    service_type: dict[str, Any] | str | None = Field(default=None, alias="ServiceType", description='Loại hình dịch vụ')
    industry: dict[str, Any] | str | None = Field(default=None, alias="Industry", description='Ngành/Lĩnh vực')
    project_type: dict[str, Any] | str | None = Field(default=None, alias="ProjectType", description='Loại công trình')
    priority: dict[str, Any] | str | None = Field(default=None, alias="Priority", description='Mức độ ưu tiên')
    funding_source: dict[str, Any] | str | None = Field(default=None, alias="FundingSource", description='Nguồn vốn dự án')
    stage: Literal['Identified', 'Qualified', 'On Hold', 'Converted', 'Dropped'] | None = Field(default=None, alias="Stage", description='Giai đoạn')
    estimated_start: datetime | None = Field(default=None, alias="EstimatedStart", description='Ngày bắt đầu dự kiến')
    estimated_end: datetime | None = Field(default=None, alias="EstimatedEnd", description='Ngày kết thúc dự kiến')
    pmo_owner: dict[str, Any] | str | int | None = Field(default=None, alias="PMOOwner", description='Quản trị PMO')

class ServiceCatalogItem(SharePointItem):
    """Danh mục dịch vụ chuẩn để liên kết vào OpportunityServices"""

    service_code: str | None = Field(default=None, alias="ServiceCode", description='ServiceCode')
    service_name: str | None = Field(default=None, alias="ServiceName", description='ServiceName')
    category: dict[str, Any] | str | None = Field(default=None, alias="Category", description='Category')
    description: str | None = Field(default=None, alias="Description", description='Description')
    is_active: bool | None = Field(default=False, alias="IsActive", description='IsActive')
    default_duration_days: float | int | None = Field(default=None, alias="DefaultDurationDays", description='DefaultDurationDays')
    default_price: float | int | None = Field(default=None, alias="DefaultPrice", description='DefaultPrice')

class ApprovalDelegationsItem(SharePointItem):
    """Ủy quyền phê duyệt tạm thời khi vắng mặt"""

    delegator: dict[str, Any] | str | int | None = Field(default=None, alias="Delegator", description='Delegator')
    delegatee: dict[str, Any] | str | int | None = Field(default=None, alias="Delegatee", description='Delegatee')
    from_date: datetime | None = Field(default=None, alias="FromDate", description='FromDate')
    to_date: datetime | None = Field(default=None, alias="ToDate", description='ToDate')
    is_active: bool | None = Field(default=False, alias="IsActive", description='IsActive')

class ApprovalHistoriesItem(SharePointItem):
    """Nhật ký lưu vết thao tác và lịch sử phê duyệt"""

    submission_id: int | dict[str, Any] | None = Field(default=None, alias="SubmissionId", description='SubmissionId')
    step_number: float | int | None = Field(default=None, alias="StepNumber", description='StepNumber')
    approver: dict[str, Any] | str | int | None = Field(default=None, alias="Approver", description='Approver')
    action: Literal['Approve', 'Reject', 'Delegate', 'RequestInfo'] | None = Field(default=None, alias="Action", description='Action')
    comment: str | None = Field(default=None, alias="Comment", description='Comment')
    timestamp: datetime | None = Field(default=None, alias="Timestamp", description='Timestamp')

class ApprovalNodesItem(SharePointItem):
    """Định nghĩa các nút duyệt từng cấp trong quy trình phê duyệt"""

    workflow_id: int | dict[str, Any] | None = Field(default=None, alias="WorkflowId", description='WorkflowId')
    step_order: float | int | None = Field(default=None, alias="StepOrder", description='StepOrder')
    approver_role: str | None = Field(default=None, alias="ApproverRole", description='ApproverRole')
    required_threshold: float | int | None = Field(default=None, alias="RequiredThreshold", description='RequiredThreshold')

class ApprovalWorkflowsItem(SharePointItem):
    """Quy trình phê duyệt"""

    workflow_name: str | None = Field(default=None, alias="WorkflowName", description='WorkflowName')
    description: str | None = Field(default=None, alias="Description", description='Description')
    steps: float | int | None = Field(default=None, alias="Steps", description='Steps')

class DynamicFormsItem(SharePointItem):
    """Cấu hình và định nghĩa biểu mẫu động"""

    form_code: str | None = Field(default=None, alias="FormCode", description='FormCode')
    form_title: str | None = Field(default=None, alias="FormTitle", description='FormTitle')
    target_list: str | None = Field(default=None, alias="TargetList", description='TargetList')
    json_schema: str | None = Field(default=None, alias="JsonSchema", description='JsonSchema')

class EnvironmentVariablesItem(SharePointItem):
    """Biến môi trường hệ thống"""

    variable_name: str | None = Field(default=None, alias="VariableName", description='VariableName')
    value: str | None = Field(default=None, alias="Value", description='Value')
    description: str | None = Field(default=None, alias="Description", description='Description')

class IntegrationPointsItem(SharePointItem):
    """Điểm tích hợp hệ thống"""

    integration_name: str | None = Field(default=None, alias="IntegrationName", description='IntegrationName')
    system_name: str | None = Field(default=None, alias="SystemName", description='SystemName')
    api_endpoint: str | None = Field(default=None, alias="APIEndpoint", description='APIEndpoint')
    auth_method: Literal['None', 'Basic', 'OAuth2', 'APIKey'] | None = Field(default=None, alias="AuthMethod", description='AuthMethod')

class SubmissionsItem(SharePointItem):
    """Hồ sơ nộp phê duyệt"""

    submission_title: str | None = Field(default=None, alias="SubmissionTitle", description='SubmissionTitle')
    related_entity: Literal['Contract', 'Invoice', 'Expense', 'Project', 'CDEDocument'] | None = Field(default=None, alias="RelatedEntity", description='RelatedEntity')
    related_id: float | int | None = Field(default=None, alias="RelatedId", description='RelatedId')
    submitted_by: dict[str, Any] | str | int | None = Field(default=None, alias="SubmittedBy", description='SubmittedBy')
    submission_date: datetime | None = Field(default=None, alias="SubmissionDate", description='SubmissionDate')
    status: dict[str, Any] | str | None = Field(default=None, alias="Status", description='Status')

class SystemSettingsItem(SharePointItem):
    """Tham số cấu hình ứng dụng và thiết lập hệ thống"""

    setting_key: str | None = Field(default=None, alias="SettingKey", description='SettingKey')
    setting_value: str | None = Field(default=None, alias="SettingValue", description='SettingValue')
    category: Literal['UI', 'Finance', 'Workflow', 'Security'] | None = Field(default=None, alias="Category", description='Category')
    is_encrypted: bool | None = Field(default=False, alias="IsEncrypted", description='IsEncrypted')


__all__ = [
    "SharePointItem",
    "AllocationRulesItem",
    "BankAccountsItem",
    "DocumentRequirementsItem",
    "ExpenseChecklistsItem",
    "ExpensesItem",
    "FinancialPlansItem",
    "InputInvoicesItem",
    "InvoiceRequestsItem",
    "OutgoingInvoicesItem",
    "SharedCostAllocationsItem",
    "VendorsItem",
    "AssetsItem",
    "BenefitPackagesItem",
    "CertificationsItem",
    "DepartmentsItem",
    "EmployeeBenefitsItem",
    "EmployeeHistoryItem",
    "EmployeesItem",
    "EmploymentContractsItem",
    "MaintenanceLogsItem",
    "ProjectMembersItem",
    "RewardsItem",
    "TimesheetsItem",
    "MeasurablesItem",
    "OKRSKeyResultsItem",
    "OKRSObjectivesItem",
    "QuartersItem",
    "ScorecardDataItem",
    "ActivitiesItem",
    "AssignmentDetailsItem",
    "CDEDocumentsItem",
    "ContractScopesItem",
    "ContractsItem",
    "JobAssignmentsItem",
    "LessonsLearnedItem",
    "ProjectHistoryItem",
    "ProjectIssuesItem",
    "ProjectRisksItem",
    "ProjectsItem",
    "ScopeDepartmentAllocationsItem",
    "WorkPackagesItem",
    "ContactsItem",
    "CustomersItem",
    "LeadsItem",
    "OpportunitiesItem",
    "OpportunityServicesItem",
    "OpportunityStageHistoryItem",
    "OpportunityStakeholdersItem",
    "PotentialProjectsItem",
    "ServiceCatalogItem",
    "ApprovalDelegationsItem",
    "ApprovalHistoriesItem",
    "ApprovalNodesItem",
    "ApprovalWorkflowsItem",
    "DynamicFormsItem",
    "EnvironmentVariablesItem",
    "IntegrationPointsItem",
    "SubmissionsItem",
    "SystemSettingsItem",
]
