"""Generator script for Pydantic v2 typed models from SharePoint List schemas.

Reads 59 JSON definitions in datamodel/sharepoint/lists/ and generates
type-safe Pydantic v2 models in tools/validator/models.py.
"""

from __future__ import annotations

import json
import keyword
import re
from pathlib import Path
from typing import Any


def to_snake_case(name: str) -> str:
    """Converts PascalCase or CamelCase string to snake_case, handling acronyms.

    Examples:
        VATRate -> vat_rate
        NationalProjectID -> national_project_id
        OpportunityName -> opportunity_name

    Args:
        name: PascalCase string.

    Returns:
        snake_case string.
    """
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    return re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s).lower()


def map_field_type(col: dict[str, Any]) -> tuple[str, str]:
    """Maps SharePoint column schema to Python type annotation and default.

    Args:
        col: Column dictionary definition.

    Returns:
        Tuple of (type_annotation_string, default_value_expression).
    """
    col_type = col.get("Type", "")

    if col_type in ("Text", "SingleLine", "Note"):
        return "str | None", "None"

    if col_type in ("Number", "Currency"):
        return "float | int | None", "None"

    if col_type == "DateTime":
        return "datetime | None", "None"

    if col_type == "Date":
        return "date | None", "None"

    if col_type in ("YesNo", "Boolean"):
        return "bool | None", "False"

    if col_type == "Choice":
        choices = col.get("Choices", [])
        if choices:
            choices_repr = ", ".join(repr(c) for c in choices)
            return f"Literal[{choices_repr}] | None", "None"
        return "str | None", "None"

    if col_type == "MultiChoice":
        choices = col.get("Choices", [])
        if choices:
            choices_repr = ", ".join(repr(c) for c in choices)
            return (
                f"list[Literal[{choices_repr}]] | list[str] | None",
                "Field(default_factory=list)",
            )
        return "list[str] | None", "Field(default_factory=list)"

    if col_type == "Lookup":
        return "int | dict[str, Any] | None", "None"

    if col_type == "User":
        if col.get("AllowMultiple"):
            return (
                "list[dict[str, Any] | str | int] | None",
                "Field(default_factory=list)",
            )
        return "dict[str, Any] | str | int | None", "None"

    if col_type in ("ManagedMetadata", "Taxonomy"):
        if col.get("AllowMultiple"):
            return "list[dict[str, Any] | str] | None", "Field(default_factory=list)"
        return "dict[str, Any] | str | None", "None"

    if col_type in ("URL", "Hyperlink"):
        return "dict[str, Any] | str | None", "None"

    return "Any", "None"


def generate_models_code(lists_dir: Path) -> str:
    """Generates Python source code for Pydantic models of all lists.

    Args:
        lists_dir: Directory containing list schema JSON files.

    Returns:
        Generated Python code as string.
    """
    json_files = sorted(lists_dir.rglob("*.json"), key=lambda p: p.as_posix())

    lines: list[str] = [
        '"""Generated Pydantic v2 models for IDOP SharePoint Lists.',
        "",
        "DO NOT EDIT DIRECTLY. Generated by scripts/generate_pydantic_models.py.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from datetime import date, datetime",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "",
        "class SharePointItem(BaseModel):",
        '    """Standard base class for all IDOP SharePoint list items."""',
        "",
        '    model_config = ConfigDict(extra="ignore", populate_by_name=True)',
        "",
        '    id: int | None = Field(default=None, alias="ID")',
        '    title: str | None = Field(default=None, alias="Title")',
        '    created: datetime | None = Field(default=None, alias="Created")',
        '    modified: datetime | None = Field(default=None, alias="Modified")',
        '    author: dict[str, Any] | str | int | None = Field(default=None, alias="Author")',
        '    editor: dict[str, Any] | str | int | None = Field(default=None, alias="Editor")',
        "",
    ]

    generated_classes: list[str] = []

    # Map to ensure deduplication if list names overlap
    seen_names: set[str] = set()

    for file_path in json_files:
        try:
            data = json.loads(file_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue

        list_name = data.get("ListName")
        if not list_name or list_name in seen_names:
            continue
        seen_names.add(list_name)

        class_name = f"{list_name}Item"
        generated_classes.append(class_name)
        description = data.get("Description", f"Model for {list_name} list.")

        lines.extend([
            "",
            f"class {class_name}(SharePointItem):",
            f'    """{description}"""',
            "",
        ])

        columns = data.get("Columns", [])
        if not columns:
            lines.append("    pass")
            continue

        for col in columns:
            col_name = col.get("Name", "")
            if not col_name:
                continue

            attr_name = to_snake_case(col_name)
            if keyword.iskeyword(attr_name):
                attr_name = f"{attr_name}_"

            type_str, default_expr = map_field_type(col)

            # Avoid re-declaring base fields if exactly same name
            if col_name in ("ID", "Title", "Created", "Modified", "Author", "Editor") and attr_name in (
                "id", "title", "created", "modified", "author", "editor"
            ):
                # Still declare if display name or custom type differs
                desc = col.get("DisplayName", col_name)
                lines.append(
                    f'    {attr_name}: {type_str} = Field(default={default_expr}, alias="{col_name}", description={repr(desc)})'
                )
                continue

            desc = col.get("DisplayName", col_name)
            if default_expr.startswith("Field("):
                lines.append(
                    f'    {attr_name}: {type_str} = {default_expr[:-1]}, alias="{col_name}", description={repr(desc)})'
                )
            else:
                lines.append(
                    f'    {attr_name}: {type_str} = Field(default={default_expr}, alias="{col_name}", description={repr(desc)})'
                )

    lines.extend([
        "",
        "",
        "__all__ = [",
        '    "SharePointItem",',
    ])
    for cls in generated_classes:
        lines.append(f'    "{cls}",')
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    """CLI entrypoint for generator."""
    repo_root = Path(__file__).resolve().parents[1]
    lists_dir = repo_root / "datamodel" / "sharepoint" / "lists"
    output_path = repo_root / "tools" / "validator" / "models.py"

    code = generate_models_code(lists_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(code, encoding="utf-8")

    print(f"✅ Generated {len(code.splitlines())} lines in {output_path.as_posix()}")
    return 0


if __name__ == "__main__":
    main()
